inventarioKK/equipo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

app_name = 'equipo'
urlpatterns = [
    path('', views.ListaDeEquipos.as_view(), name='lista_de_equipos'),
    path('inicio/', views.Inicio.as_view(), name='inicio'),
    path('nuevo_equipo/', views.EquipoCreate.as_view(), name='nuevo_equipo'),
    path('busqueda_equipo/', views.BusquedaEquipo.as_view(), name='busqueda_equipo'),
    path('generador/', views.generador, name='generador'),
    path('<str:pk>/', views.DescripcionEquipo.as_view(), name='des_equipo'),
    path('editar_equipo/<str:pk>/', views.EquipoUpdate.as_view(), name='editar_equipo'),
    
]

inventarioKK/inventarioKK/urls.py
from django.contrib.auth.views import LoginView, logout_then_login, login_required
"""inventarioKK URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from equipo import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('empleado/', include('empleado.urls')),
    path('equipo/', include('equipo.urls')),
    path('mantenimiento/', include('mantenimiento.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.Inicio.as_view(), name = 'inicio'),
]

inventarioKK/mantenimiento/urls.py
"""urls de mantenimiento"""
from django.urls import path
from . import views

app_name = 'mantenimiento'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('generador/', views.generador, name='generador'),
    path('generador_bodega/', views.generador_bodega, name='generador_bodega'),
    path('busqueda_mantenimiento/', views.BusquedaMantenimiento.as_view(), name='busqueda_mantenimiento'),
    path('nuevo_mantenimiento/', views.MantenimientoCreate.as_view(), name='nuevo'),
    path('index_bodega/', views.BodegaIndex.as_view(), name='index_bodega'),
    path('nuevo_bodega/', views.BodegatoCreate.as_view(), name='nuevo_bodega'),
    path('busqueda_bodega/', views.BodegaBusqueda.as_view(), name='busqueda_bodega'),
    path('nuevo_mantenimientoporbodega/', views.MantenimientoPorBodegaCreate.as_view(), name='nuevo_mantenimientoporbodega'),
    path('editar_mantenimiento/<str:pk>/', views.MantenimientoUpdate.as_view(), name='editar'),
    path('descripcion_mantenimiento/<str:pk>/', views.DescripcionMatenimiento.as_view(), name='descripcion'),
    path('<str:pk>/', views.DescripcionMatenimiento.as_view(), name='descripcion'),
    path('editar_bodega/<str:pk>/', views.BodegatoUpdate.as_view(), name='editar_bodega'),
    path('descripcion_bodega/<str:pk>/', views.BodegaDescripcion.as_view(), name='descripcion_bodega'),
    


]

inventarioKK/mantenimiento/models.py
"""Modelos de Mantenimiento"""
from django.db import models
from equipo.models import Equipo
from empleado.models import Empleado

# Create your models here.
class TipoMantenimiento(models.Model):
    """Modelo para Tipo de Mantenimiento (Correctivo, Preventivo o Innovativo)"""
    id_tipo_mantenimiento = models.AutoField(primary_key=True)
    nombre_tipo_mantenimiento = models.CharField(max_length=45)
    subtipo_mantenimiento = models.CharField(max_length=45, blank=True, null=True)
    descripcion = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'tipo_mantenimiento'

    def __str__(self):
        return str(self.nombre_tipo_mantenimiento) + " - " + str(self.subtipo_mantenimiento)

class Mantenimiento(models.Model):
    """Modelo mantenimiento que utilizar modelo equipo importado de la app equipo"""
    id_mantenimiento = models.CharField(primary_key=True, max_length=8)
    fecha = models.DateField()
    descripcion = models.CharField(max_length=60)
    id_empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, db_column='id_empleado')
    id_equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE, db_column='id_equipo')
    id_tipo_mantenimiento = models.ForeignKey(TipoMantenimiento, on_delete=models.CASCADE, db_column='id_tipo_mantenimiento')

    class Meta:
        managed = True
        db_table = 'mantenimiento'

    def __str__(self):
        return str(self.id_mantenimiento) + " - " + str(self.id_equipo.id_tipo_equipo.nombre_tipo_equipo) + " - " + str(self.id_empleado.nombre) + " " + str(self.id_empleado.apellido)

class TipoRecurso(models.Model):
    """Modelo para Tipo de Recurso"""
    id_tipo_recurso = models.AutoField(primary_key=True)
    nombre_tipo_recurso = models.CharField(max_length=45)

    class Meta:
        managed = True
        db_table = 'tipo_recurso'

    def __str__(self):
        return str(self.nombre_tipo_recurso)

class Bodega(models.Model):
    """Modelo para Bodega"""
    id_bodega = models.CharField(primary_key=True, max_length=7)
    nombre_recurso = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=45, blank=True, null=True)
    id_tipo_recurso = models.ForeignKey(TipoRecurso, on_delete=models.CASCADE, db_column='id_tipo_recurso')

    class Meta:
        managed = True
        db_table = 'bodega'

    def __str__(self):
        return str(self.id_bodega) + " - " + str(self.nombre_recurso)

class MantenimientoPorBodega(models.Model):
    """Modelo para Mantenimiento por Recurso"""
    id_mantenimiento_por_bodega = models.AutoField(primary_key=True)
    id_mantenimiento = models.ForeignKey(Mantenimiento, on_delete=models.CASCADE, db_column='id_mantenimiento')
    id_bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE, db_column='id_bodega')

    class Meta:
        managed = True
        db_table = 'tipo_mantenimiento_por_recurso'
        unique_together = (('id_mantenimiento', 'id_bodega'),)

    def __str__(self):
        return 'M: ' + str(self.id_mantenimiento) + " - MxB: " + str(self.id_mantenimiento_por_bodega) + " - B: " + str(self.id_bodega)

inventarioKK/mantenimiento/views.py
"""Vistas de Mantenimiento"""
from django.views import generic
from django.urls import reverse_lazy
from django.db.models import Q
from datetime import datetime
from datetime import date
from django.http import HttpResponse, HttpResponseRedirect
from .models import Mantenimiento, Empleado, Equipo, TipoMantenimiento, Bodega, MantenimientoPorBodega
from .forms import MantenimientoForm, BodegaForm, MantenimientoPorBodegaForm
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class Index(LoginRequiredMixin, generic.ListView):
    """Vista generica Index"""
    # Matenimiento.objects.all()
    paginate_by = 5
    template_name = 'mantenimiento/index.html'
    context_object_name = 'tabla_mantenimiento'
    model = Mantenimiento

class DescripcionMatenimiento(LoginRequiredMixin, generic.DetailView):
    """Vista generica de los matenimientos realizados a un equipo"""
    # Mantenimiento.objects.get(pk=1)
    model = Mantenimiento
    template_name = 'mantenimiento/descripcion.html'
    context_object_name = 'descripcion_mantenimiento'

class MantenimientoUpdate(LoginRequiredMixin, generic.UpdateView):
    """Actualiza el registro de un equipo"""
    model = Mantenimiento
    form_class = MantenimientoForm
    template_name = 'mantenimiento/nuevo_mantenimiento.html'
    success_url = reverse_lazy('mantenimiento:index')

class MantenimientoCreate(LoginRequiredMixin, generic.CreateView):
    """Vista para agregar un registro de mantenimiento"""
    model = Mantenimiento
    form_class = MantenimientoForm
    context_object_name = 'mantenimiento_objeto'
    template_name = 'mantenimiento/nuevo_mantenimiento.html'
    success_url = reverse_lazy('mantenimiento:index')

class BusquedaMantenimiento(LoginRequiredMixin, generic.ListView):
    """Busca un Mantenimiento"""
    model = Mantenimiento
    context_object_name = 'mantenimiento_objeto'
    template_name = 'mantenimiento/busqueda_mantenimiento.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Mantenimiento.objects.filter(
            Q(id_mantenimiento__icontains=query) | Q(fecha__icontains=query) | Q(descripcion__icontains=query) |
            Q(id_empleado__id_empleado__icontains=query) | Q(id_equipo__id_equipo__icontains=query) | 
            Q(id_tipo_mantenimiento__nombre_tipo_mantenimiento__icontains=query) | Q(id_tipo_mantenimiento__id_tipo_mantenimiento__icontains=query) |
            Q(id_empleado__nombre__icontains=query)
        ) 
        return object_list

def generador(request):
    """
    Termina de generar codigo
    """
    if request.method == 'POST':
        print('llego')
        if 'letras' in request.POST:
            letras = request.POST['letras'].upper()
            anio = str(date.today().year)[:2]
            numero = str(Mantenimiento.objects.filter(id_mantenimiento__startswith=letras+anio)
                         .count()+1).zfill(3)
            codigo = letras+anio+numero
            return HttpResponse(codigo)
    return HttpResponse('FAIL!!!!!')

class BodegaIndex(LoginRequiredMixin, generic.ListView):
    """Vista generica del Indice de la Bodega"""
    # Bodega.objects.all()
    paginate_by = 5
    template_name = 'mantenimiento/index_bodega.html'
    context_object_name = 'tabla_bodega'
    model = Bodega

class BodegaDescripcion(LoginRequiredMixin, generic.DetailView):
    """Vista generica de los detalles del recurso en bodega seleccionado"""
    # Bodega.objects.get(pk=1)
    model = Bodega
    template_name = 'mantenimiento/detalle_bodega.html'
    context_object_name = 'descripcion_bodega'

class BodegatoUpdate(LoginRequiredMixin, generic.UpdateView):
    """Actualiza el registro de un recurso en bodega"""
    model = Bodega
    form_class = BodegaForm
    template_name = 'mantenimiento/nuevo_bodega.html'
    success_url = reverse_lazy('mantenimiento:index_bodega')

class BodegatoCreate(LoginRequiredMixin, generic.CreateView):
    """Vista para agregar un registro en bodega"""
    model = Bodega
    form_class = BodegaForm
    context_object_name = 'mantenimiento_objeto'
    template_name = 'mantenimiento/nuevo_bodega.html'
    success_url = reverse_lazy('mantenimiento:index_bodega')

class BodegaBusqueda(LoginRequiredMixin, generic.ListView):
    """Busca un Recurso en Bodega"""
    model = Bodega
    context_object_name = 'bodega_objeto'
    template_name = 'mantenimiento/busqueda_bodega.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Bodega.objects.filter(
            Q(id_bodega__icontains=query) | Q(nombre_recurso__icontains=query) | 
            Q(descripcion__icontains=query) | Q(id_tipo_recurso__nombre_tipo_recurso__icontains=query)
        ) 
        return object_list

def BodegaPDF(request, id_bodega):
    """Muestra al Recurso en Bodega seleccionado en un PDF y las opciones de Guardar dicho PDF y/o Imprimirlo"""
    descripcion_bodega = Bodega.objects.get(pk=id_bodega)
    hora = datetime.now()
    """format = hora.strftime('Día :%d, Mes: %m, Año: %Y, Hora: %H, Minutos: %M')"""
    data = {
            'descripcion_bodega': descripcion_bodega,
            'fechaHora' : hora,
            
        }
    pdf = render_to_pdf('mantenimiento/pdf_bodega.html', data)
    return HttpResponse(pdf, content_type='application/pdf')


def generador_bodega(request):
    """
    Termina de generar codigo
    """
    if request.method == 'POST':
        print('llego a obtener bodega')
        if 'letras' in request.POST:
            letras = request.POST['letras'].upper()
            anio = str(date.today().year)[:2]
            numero = str(Bodega.objects.filter(id_bodega__startswith=letras+anio)
                         .count()+1).zfill(3)
            codigo = letras+anio+numero
            return HttpResponse(codigo)
    return HttpResponse('FAIL!!!!!')

class MantenimientoPorBodegaCreate(LoginRequiredMixin, generic.CreateView):
    """
    crea mantenimientos por bodega
    """
    model = MantenimientoPorBodega
    form_class = MantenimientoPorBodegaForm
    context_object_name = 'mantenimientoporbodega_objeto'
    template_name = 'mantenimiento/nuevo_mantenimientoporbodega.html'
    success_url = reverse_lazy('mantenimiento:index')

inventarioKK/templates/mantenimiento/busqueda_bodega.html
{% extends "mantenimiento/layout_base_mantenimiento.html"%}
{% block title %}Resultados de la Busqueda{% endblock %}
{% load static %}
{% block body %}
<style>

  .search_submit{
      
      font-size: 15px;
     
    }
</style>

<br>
<div class="container">
   
    <h1 class="text-center">Resultados de la Búsqueda</h1>
    <!--SearchBox con su respectivo Botón-->
<div class="text-right">
<form action="{% url 'mantenimiento:busqueda_bodega' %}"  method="get">
    <input name="q" type="text" placeholder="Buscar recurso...">
    <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
</form>
</div>
<br>
        <div class="row justify-content-md-center text-right">
            <button class="button button2 align-right"><a href="{% url 'mantenimiento:index_bodega' %}" style="color: white;">Regresar</a></button>
        </div>
 <!--Tabla-->
    {% if object_list %}
    <table class="table table-bordered text-center table-hover table-dark">
        <thead>
          <tr>
            <th scope="col">N° de Registro</th>
            <th scope="col">Nombre</th>
            <th scope="col">Descripción</th>
            <th scope="col">Tipo de Recurso</th>
            <th scope="col">Opciones</th>
          </tr>
        </thead>
        <tbody>

    {% for recurso in object_list %}
        
    <tr>
      <th scope="row">{{recurso.id_bodega}}</th>
      <td>{{recurso.nombre_recurso}}</td>
      <td>{{recurso.descripcion}}</td>
      <td>{{recurso.id_tipo_recurso}}</td>
      <td><a href="{% url 'mantenimiento:descripcion_bodega' recurso.id_bodega %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
          <a href="{% url 'mantenimiento:editar_bodega' recurso.id_bodega %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
          
      </td>
    </tr>
    {% endfor %}
{% else %}
<div class="text-center">
<h1>No hay coincidencias!</h1>
<img src="{% static 'img\rocket.gif' %}" alt="cohete">
</div>
{% endif %}
</tbody>
</table>
    </div>
{% endblock %}

inventarioKK/templates/mantenimiento/busqueda_mantenimiento.html
{% extends "mantenimiento/layout_base_mantenimiento.html"%}
{% block title %}Resultados de la Busqueda{% endblock %}
{% load static %}
{% block body %}

<style>
  
  
  .search_submit{
      
      font-size: 15px;
     
    }
  
  </style>

<br>
<div class="container">
   
    <h1 class="text-center">Resultados de la Búsqueda</h1>
    <!--SearchBox con su respectivo Botón-->
<div class="text-right">
<form action="{% url 'mantenimiento:busqueda_mantenimiento' %}"  method="get">
    <input name="q" type="text" placeholder="Buscar mantenimiento...">
    <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
</form>
</div>
<br>

        <div class="row justify-content-md-center text-right">
            <button class="button button2 align-right"><a href="{% url 'mantenimiento:index' %}" style="color: white;">Regresar</a></button>
        </div>

 <!--Tabla-->
    {% if object_list %}
    <table class="table table-bordered table-hover table-dark">
        <thead>
          <tr>
            <th scope="col">N° de Registro</th>
            <th scope="col">Empleado</th>
            <th scope="col">Equipo</th>
            <th scope="col">Fecha</th>
            <th scope="col">Tipo Mantenimiento</th>
            <th scope="col">Opciones</th>
          </tr>
        </thead>
        <tbody>

    {% for mantenimiento in object_list %}
        
    <tr>
      <th scope="row">{{mantenimiento.id_mantenimiento}}</th>
      <td>{{mantenimiento.id_empleado}}</td>
      <td>{{mantenimiento.id_equipo}}</td>
      <td>{{mantenimiento.fecha}}</td>
      <td>{{mantenimiento.id_tipo_mantenimiento}}</td>
      <td><a href="{% url 'mantenimiento:descripcion' mantenimiento.id_mantenimiento %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
          <a href="{% url 'mantenimiento:editar' mantenimiento.id_mantenimiento %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
          
      </td>
    </tr>
    {% endfor %}
{% else %}
<div class="text-center">
<h1>No hay coincidencias!</h1>
<img src="{% static 'img\rocket.gif' %}" alt="cohete">

</div>
{% endif %}
</tbody>
</table>
    </div>
{% endblock %}

inventarioKK/templates/mantenimiento/descripcion.html
{% extends "mantenimiento/layout_base_mantenimiento.html"%}
{% load static %}
{% block title %}Descripcion Mantenimiento{% endblock %}
{% block body %}
<h1 class="text-center">Detalles de Mantenimiento</h1>
<br>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <!--Tabla-->
            {% if descripcion_mantenimiento %}
                <table class="table table-bordered table-hover table-dark text-center">
                    <thead>
                    <tr>
                        <th scope="col">Atributos</th>
                        <th scope="col">Datos</th>
                    </tr>
                    </thead>
                    <tbody>
                
                        <tr>
                            <th scope="row">Código</th> 
                            <td>{{descripcion_mantenimiento.id_mantenimiento}}</td>      
                        </tr>
                        <tr>
                            <th scope="row">Tipo de Mantenimiento:</th>
                            <td>{{descripcion_mantenimiento.id_tipo_mantenimiento}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Fecha:</th>
                            <td>{{descripcion_mantenimiento.fecha}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Descripcion:</th>
                            <td>{{descripcion_mantenimiento.descripcion}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Responsable:</th>
                            <td>{{descripcion_mantenimiento.id_empleado}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Equipo:</th>
                            <td>{{descripcion_mantenimiento.id_equipo}}</td>
                        </tr>
                    {% if descripcion_mantenimiento.mantenimientoporbodega_set.all %}
                    {% for recurso in descripcion_mantenimiento.mantenimientoporbodega_set.all %}
                        <tr>
                            <th scope="row">Recurso #{{forloop.counter}}:</th>
                            <td>{{recurso.id_bodega}}</td>
                        </tr>
                    {% endfor %}
                    {% else %}
                        <tr>
                            <th scope="row">Recursos:</th>
                            <td>No Asignados</td>
                        </tr>
                    {% endif %}

                        <tr>
                            <th scope="row">Acciones:</th>
                            <td><a href="{% url 'mantenimiento:editar' descripcion_mantenimiento.id_mantenimiento %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
                            </td>
                        </tr>
            {% else %}
                <h1 class="text-center">No hay mantenimientos registrados</h1>
            {% endif %}
                </tbody>
            </table>
            <div class="row justify-content-md-center">
                <button type="button" class="button button2 "><a href="{% url 'mantenimiento:index' %}" style="color: white;">Regresar</a></button>
                <button type="button" class="button button1 "><a href="{% url 'mantenimiento:pdf_mantenimiento' descripcion_mantenimiento.id_mantenimiento %}" style="color: white;">Imprimir</a></button>
            </div>
        </div>
    </div>
</div>
  
{% endblock %}

inventarioKK/templates/mantenimiento/index.html
{% extends "mantenimiento/layout_base_mantenimiento.html"%}
{% load static %}
{% block title %}Mantenimiento{% endblock %}
{% block body %}

<style>
.button{
    transition-duration: 0.4s; 
    border: 2px solid #000000;
    border-radius: 12px;
   }
.button:hover{
  color: #999999;
  background-color: #ffffff;
}
.search_submit{
      
      font-size: 15px;
     
    }
</style>

<br>
<div class = 'container'>
  <h1 class="text-center">Mantenimientos Realizados</h1>
  <div class = 'text-right'>
    <form action="{% url 'mantenimiento:busqueda_mantenimiento' %}" method="get">
      <input name="q" type="text" placeholder="Buscar Mantenimientos...">
      <button type="submit reset" class="btn btn-dark search_submit">Buscar</button>
    </form>
  </div>
  <br>
  {% if tabla_mantenimiento %}
  <table class="table table-dark text-center table-hover">
      <thead>
        <tr>
          <th scope="col">N° de Registro</th>
          <th scope="col">Empleado</th>
          <th scope="col">Equipo</th>
          <th scope="col">Fecha</th>
          <th scope="col">Tipo Mantenimiento</th>
          <th scope="col">Opciones</th>
        </tr>
      </thead>
      <tbody>
        {% for tabla in tabla_mantenimiento %}
        <tr>
          <th scope="row">{{tabla.id_mantenimiento}}</th>
          <td>{{tabla.id_empleado}}</td>
          <td>{{tabla.id_equipo}}</td>
          <td>{{tabla.fecha}}</td>
          <td>{{tabla.id_tipo_mantenimiento}}</td>
          <td>
            <a href="{% url 'mantenimiento:descripcion' tabla.id_mantenimiento %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
            <a href="{% url 'mantenimiento:editar' tabla.id_mantenimiento %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
  </table>
  {% else %}
  <p>No hay registros de Mantenimientos</p>
  {% endif %}

    <!--Paginación-->
    <div class="row justify-content-md-center">
      <ul class="pagination">
      {% if page_obj.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page=1" aria-label="Previous">
                  Primera
              </a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
          {% ifequal num page_obj.number %}
          <li class="page-item active" aria-current="page">
              <a class="page-link current">
                  {{ num }}
                  <span class="sr-only">(current)</span>
              </a>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
          {% endifequal %} 
      {% endfor %}        

      {% if page_obj.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&raquo;</span>
              </a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Previous">
                  Última
              </a>
          </li>
      {% endif %}
      </ul>
  </div>
</div>
{% endblock %}

inventarioKK/templates/mantenimiento/index_bodega.html
{% extends "mantenimiento/layout_base_mantenimiento.html"%}
{% load static %}
{% block title %}Indice de Bodega{% endblock %}
{% block body %}
<style>

  .search_submit{
      
      font-size: 15px;
     
    }
</style>

<br>
<div class = 'container'>
  <h1 class="text-center">Recursos en Bodega</h1>
  <div class = 'text-right'>
    <form action="{% url 'mantenimiento:busqueda_bodega' %}" method="get">
      <input name="q" type="text" placeholder="Buscar recursos...">
      <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
    </form>
  </div>
  <br>

<!--Tabla-->
  {% if tabla_bodega %}
  <table class="table table-dark text-center table-hover">
      <thead>
        <tr>
          <th scope="col">N° de Registro</th>
          <th scope="col">Nombre</th>
          <th scope="col">Descripcion</th>
          <th scope="col">Tipo de Recurso</th>
        </tr>
      </thead>
      <tbody>
        {% for tabla in tabla_bodega %}
        <tr>
          <th scope="row">{{tabla.id_bodega}}</th>
          <td>{{tabla.nombre_recurso}}</td>
          <td>{{tabla.descripcion}}</td>
          <td>{{tabla.id_tipo_recurso}}</td>
          <td>
            <a href="{% url 'mantenimiento:descripcion_bodega' tabla.id_bodega %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
            <a href="{% url 'mantenimiento:editar_bodega' tabla.id_bodega %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
  </table>
  {% else %}
  <p>No hay recursos en bodega!</p>
  {% endif %}

    <!--Paginación-->
    <div class="row justify-content-md-center">
      <ul class="pagination">
      {% if page_obj.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page=1" aria-label="Previous">
                  Primera
              </a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
          {% ifequal num page_obj.number %}
          <li class="page-item active" aria-current="page">
              <a class="page-link current">
                  {{ num }}
                  <span class="sr-only">(current)</span>
              </a>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
          {% endifequal %} 
      {% endfor %}        

      {% if page_obj.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&raquo;</span>
              </a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Previous">
                  Última
              </a>
          </li>
      {% endif %}
      </ul>
  </div>
</div>
{% endblock %}

inventarioKK/templates/mantenimiento/layout_base_mantenimiento.html
{% extends "layout_base.html"%}
{% block link_css %} 
    {% load static %}
    <link rel="stylesheet" href="{% static 'equipo/css/estilos.css' %}"> 
{% endblock %}
{% block title %}{% endblock %}
{% block body %}{% endblock %}