inventarioKK/empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleado'
urlpatterns = [
    path('', views.Indice.as_view(), name='mensaje_empleado'),
    path('busqueda_empleado/', views.BusquedaEmpleado.as_view(), name='busqueda_empleado'),
    path('nuevo_empleado/', views.CrearEmpleado.as_view(), name='nuevo_empleado'),
    path('generador/', views.generador, name='generador'),
    path('<str:pk>/', views.DescripcionEmpleado.as_view(), name='des_em'),
    path('editar_empleado/<str:pk>/', views.EditarEmpleado.as_view(), name='editar_empleado'),
    path('eliminar_empleado/<str:pk>/', views.EliminarEmpleado.as_view(), name='eliminar_empleado'),
]

inventarioKK/equipo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

app_name = 'equipo'
urlpatterns = [
    path('', views.ListaDeEquipos.as_view(), name='lista_de_equipos'),
    path('inicio/', views.Inicio.as_view(), name='inicio'),
    path('nuevo_equipo/', views.EquipoCreate.as_view(), name='nuevo_equipo'),
    path('busqueda_equipo/', views.BusquedaEquipo.as_view(), name='busqueda_equipo'),
    path('generador/', views.generador, name='generador'),
    path('<str:pk>/', views.DescripcionEquipo.as_view(), name='des_equipo'),
    path('editar_equipo/<str:pk>/', views.EquipoUpdate.as_view(), name='editar_equipo'),
    
]

inventarioKK/inventarioKK/urls.py
from django.contrib.auth.views import LoginView, logout_then_login, login_required
"""inventarioKK URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from equipo import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('empleado/', include('empleado.urls')),
    path('equipo/', include('equipo.urls')),
    path('mantenimiento/', include('mantenimiento.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.Inicio.as_view(), name = 'inicio'),
]

inventarioKK/mantenimiento/urls.py
"""urls de mantenimiento"""
from django.urls import path
from . import views

app_name = 'mantenimiento'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('generador/', views.generador, name='generador'),
    path('generador_bodega/', views.generador_bodega, name='generador_bodega'),
    path('busqueda_mantenimiento/', views.BusquedaMantenimiento.as_view(), name='busqueda_mantenimiento'),
    path('nuevo_mantenimiento/', views.MantenimientoCreate.as_view(), name='nuevo'),
    path('index_bodega/', views.BodegaIndex.as_view(), name='index_bodega'),
    path('nuevo_bodega/', views.BodegatoCreate.as_view(), name='nuevo_bodega'),
    path('busqueda_bodega/', views.BodegaBusqueda.as_view(), name='busqueda_bodega'),
    path('nuevo_mantenimientoporbodega/', views.MantenimientoPorBodegaCreate.as_view(), name='nuevo_mantenimientoporbodega'),
    path('editar_mantenimiento/<str:pk>/', views.MantenimientoUpdate.as_view(), name='editar'),
    path('descripcion_mantenimiento/<str:pk>/', views.DescripcionMatenimiento.as_view(), name='descripcion'),
    path('<str:pk>/', views.DescripcionMatenimiento.as_view(), name='descripcion'),
    path('editar_bodega/<str:pk>/', views.BodegatoUpdate.as_view(), name='editar_bodega'),
    path('descripcion_bodega/<str:pk>/', views.BodegaDescripcion.as_view(), name='descripcion_bodega'),
    


]

inventarioKK/equipo/models.py
from django.db import models

# Create your models here.
class Marca(models.Model):
    id_marca = models.AutoField(primary_key=True)
    nombre_marca = models.CharField(max_length=45)
    soporte_tecnico = models.CharField(max_length=9, blank=True, null=True)
    

    class Meta:
        managed = True
        db_table = 'marca'

    def __str__(self):
        return str(self.nombre_marca)

class TipoEquipo(models.Model):
    id_tipo_equipo = models.AutoField(primary_key=True)
    nombre_tipo_equipo = models.CharField(max_length=45)

    class Meta:
        managed = True
        db_table = 'tipo_equipo'

    def __str__(self):
        return str(self.nombre_tipo_equipo)


class Edificio(models.Model):
    id_edificio = models.AutoField(primary_key=True)
    nombre_edificio = models.CharField(max_length=45)
    tipo_infraestructura = models.CharField(max_length=45)
    anho_construccion = models.CharField(max_length=4, blank=True, null=True)
    numero_empleados = models.CharField(max_length=4)
    capacidad_maxima = models.CharField(max_length=4)
    observaciones = models.CharField(max_length=45)

    class Meta:
        managed = True
        db_table = 'edificio'


    def __str__(self):
        return str(self.nombre_edificio)

class Ubicacion(models.Model):
    id_ubicacion = models.AutoField(primary_key=True)
    nombre_ubicacion = models.CharField(max_length=45)
    telefono_fijo = models.CharField(max_length=9, blank=True, null=True)
    id_edificio = models.ForeignKey(Edificio, on_delete=models.CASCADE, db_column='id_edificio')


    class Meta:
        managed = True
        db_table = 'ubicacion'
        unique_together = (('id_ubicacion', 'id_edificio'),)

    def __str__(self):
        return str(self.nombre_ubicacion)


class EstadoEquipo(models.Model):
    id_estado_equipo = models.AutoField(primary_key=True)
    nombre_estado_equipo = models.CharField(max_length=45)

    class Meta:
        managed = True
        db_table = 'estado_equipo'

    def __str__(self):
        return str(self.nombre_estado_equipo)


class Equipo(models.Model):
    id_equipo = models.CharField(primary_key=True, max_length=8)
    modelo = models.CharField(max_length=45)
    descripcion = models.TextField(blank=True, null=True)
    anho_fabricacion = models.CharField(max_length = 4, blank=True, null=True)
    id_tipo_equipo = models.ForeignKey(TipoEquipo, on_delete=models.CASCADE, db_column='id_tipo_equipo')
    id_marca = models.ForeignKey(Marca, on_delete=models.CASCADE, db_column='id_marca')
    id_estado_equipo = models.ForeignKey(EstadoEquipo, on_delete=models.CASCADE, db_column='id_estado_equipo')
    id_ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE, db_column='id_ubicacion')
    

    class Meta:
        managed = True
        db_table = 'equipo'
        unique_together = (('id_equipo', 'id_tipo_equipo','id_marca','id_estado_equipo','id_ubicacion'),)

    def __str__(self):
        return str(self.id_equipo)

inventarioKK/equipo/forms.py
from django import forms
from .models import Equipo

class EquipoForm(forms.ModelForm):
    """Formulario para agregar un nuevo equipo"""
    class Meta:
        """Especificaciones"""
        model = Equipo

        fields = [
            'id_equipo',
            'id_tipo_equipo',
            'modelo',
            'id_marca',
            'id_estado_equipo',
            'id_ubicacion',
            'descripcion',
            'anho_fabricacion',
         ]

        labels = {
            'id_tipo_equipo':'Tipo del equipo',
            'id_marca':'Marca',
            'id_estado_equipo':'Estado del equipo',
            'id_ubicacion':'Ubicacion',
            'descripcion':'Descripcion',
        }

        widgets = {
            'id_equipo':forms.TextInput(attrs={'class':'form-control',
                                               'type':'text',
                                               'placeholder':'codigo',
                                               'name':'id_equipo',
                                               'id':'id_equipo',
                                               'readonly':'readonly'}),
            'modelo':forms.TextInput(attrs={'class':'form-control',
                                               'type':'text',
                                               'placeholder':'modelo'}),
            'id_tipo_equipo':forms.Select(attrs={'class':'custom-select',
                                          'name':'tipo del equipo',
                                          'id':'tipo_equipo',
                                          'onchange':'SelectPasarValorEquipo("tipo_equipo","marca","ubicacion","id_equipo","/equipo/generador/")'}),
            'id_marca':forms.Select(attrs={'class':'custom-select',
                                               'name':'marca',
                                               'id':'marca',
                                               'onchange':'SelectPasarValorEquipo("tipo_equipo","marca","ubicacion","id_equipo","/equipo/generador/")'}),
            'id_estado_equipo':forms.Select(attrs={'class':'custom-select',
                                                  'name':'estado del equipo'}),
            'id_ubicacion':forms.Select(attrs={'class':'custom-select',
                                               'name':'ubicacion',
                                               'id':'ubicacion',
                                               'onchange':'SelectPasarValorEquipo("tipo_equipo","marca","ubicacion","id_equipo","/equipo/generador/")'}),
            'descripcion':forms.TextInput(attrs={'class':'form-control',
                                              'type':'text',
                                              'placeholder':'Descripcion del equipo',
                                              'name':'descripcion'}),
            'anho_fabricacion':forms.TextInput(attrs={'class':'form-control',
                                               'type':'text',
                                               'placeholder':'Año Fabricacion'}),
        }

inventarioKK/equipo/views.py
from django.shortcuts import render
from .models import Equipo, Edificio
from django.views import generic, View
from .forms import EquipoForm
from django.urls import reverse_lazy
from django.db.models import Q
from django.http import HttpResponse
from datetime import datetime
from datetime import date
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class Inicio(LoginRequiredMixin, generic.ListView):
    template_name= 'equipo/inicio.html'
    context_object_name = 'lista_equipo'
    model = Equipo

class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

class ListaDeEquipos(LoginRequiredMixin, generic.ListView):
    """vista generica tabla equipos"""
    paginate_by = 5
    template_name = 'equipo/index.html'
    context_object_name = 'lista_equipo'
    model = Equipo
   
class EquipoCreate(LoginRequiredMixin, generic.CreateView):
    """Crear un nuevo equipo"""
    model = Equipo
    form_class = EquipoForm
    template_name = 'equipo/nuevo_equipo.html'
    success_url = reverse_lazy('equipo:lista_de_equipos')

class DescripcionEquipo(LoginRequiredMixin, generic.DetailView):
    """Muestra una descripcion de cada Equipo"""
    template_name = 'equipo/descripcion_equipo.html'
    context_object_name = 'descripcion_equipo'
    model = Equipo


class EquipoUpdate(LoginRequiredMixin, generic.UpdateView):
    """Actualiza el registro de un equipo"""
    model = Equipo
    form_class = EquipoForm
    template_name = 'equipo/nuevo_equipo.html'
    success_url = reverse_lazy('equipo:lista_de_equipos')

class BusquedaEquipo(LoginRequiredMixin, generic.ListView):
    """Busca un Equipo"""
    model = Equipo
    context_object_name = 'busqueda_equipo'
    template_name = 'equipo/busqueda_equipo.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Equipo.objects.filter(
           Q(id_equipo__icontains=query) | Q(id_tipo_equipo__nombre_tipo_equipo__icontains=query) | Q(id_marca__nombre_marca__icontains=query)| 
           Q(id_estado_equipo__nombre_estado_equipo__icontains=query) | Q(descripcion__icontains=query) | Q(id_ubicacion__nombre_ubicacion__icontains=query) | Q(id_ubicacion__id_edificio__nombre_edificio__icontains=query) 
        )
        return object_list


def loginpage(request):
    userlogin = "admin"
    passw = "admin"
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        

        if userlogin == username and passw == password:
            """login(request, user)"""
            return redirect('equipo:lista_de_equipos')
        else:
            messages.info(request, 'Usuario o contraseña incorrectos')

    context = {}
    return render(request, 'equipo/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('equipo:login')

def generador(request):
    """
    Termina de generar codigo
    """
    if request.method == 'POST':
        print('llego')
        if 'letras' in request.POST:
            letras = request.POST['letras'].upper()
            anio = str(date.today().year)[:2]
            numero = str(Equipo.objects.filter(id_equipo__startswith=letras+anio).count()+1).zfill(3)
            codigo = letras+anio+numero
            return HttpResponse(codigo)
    return HttpResponse('FAIL!!!!!')

def QR(request, id_equipo):
    descripcion_equipo = Equipo.objects.get(pk=id_equipo)
    img=qrcode.make(f'equipo/{id_equipo}')
    data = {
            'descripcion_equipo': descripcion_equipo,
            'img' : img,
            
        }
    
    return HttpResponse(img.show('code.png'))

inventarioKK/templates/equipo/busqueda_equipo.html
{% extends "equipo/layout_base_equipo.html"%}
{% load static %}
{% block title %}Busquedas{% endblock %}
{% block body %}
<style>

    .search_submit{
        
        font-size: 15px;
       
      }
    
    </style>
    <div class="container">
    {% if object_list %}
    <h1 class = 'text-center'>BUSQUEDAS</h1>
    <!--SearchBox con su respectivo Botón-->
    <div class="text-right">
        <form action="{% url 'mantenimiento:busqueda_mantenimiento' %}"  method="get">
            <input name="q" type="text" placeholder="Buscar mantenimiento...">
            <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
        </form>
    </div>
    <br>
        <div class="row justify-content-md-center text-right">
            <button class="button button2 align-right"><a href="{% url 'equipo:lista_de_equipos' %}" style="color: white;">Regresar</a></button>
        </div>

        <div class = 'container'>
            <table class="table table-dark text-center table-hover">
                <thead>
                <tr>
                    <th scope="col">N° REGISTRO</th>
                    <th scope="col">TIPO DE EQUIPO</th>
                    <th scope="col">MARCA</th>
                    <th scope="col">ESTADO DEL EQUIPO</th>
                    <th scope="col">DESCRIPCION</th>
                    <th scope="col">UBICACION</th>
                    <th scope="col">EDIFICIO</th>
                    <th scope="col">OPCIONES</th>
                </tr>
                </thead>
                <tbody>
               
                {% for equipo in object_list %}
                <tr>
                    <th scope="row">{{equipo.id_equipo}}</th>
                    <td>{{equipo.id_tipo_equipo}}</td>
                    <td>{{equipo.id_marca}}</td>
                    <td>{{equipo.id_estado_equipo}}</td>
                    <td>{{equipo.descripcion}}</td>
                    <td>{{equipo.id_ubicacion}}</td>
                    <td>{{equipo.id_ubicacion.id_edificio}}</td>
                    <td><a href="{% url 'equipo:des_equipo' equipo.id_equipo %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
                        <a href="{% url 'equipo:editar_equipo' equipo.id_equipo %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
                    </td>
                </tr>
                 {% endfor %}
    {% else %}
        <h1>No se encontraron equipos!</h1>
        <div class="text-right">
            <form action="{% url 'equipo:busqueda_equipo' %}"  method="get">
                <input name="q" type="text" placeholder="Buscar equipos...">
                <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
            </form>
        </div>
        <br>
        <img src="{% static 'img\rocket.gif' %}" alt="cohete">
        
    {% endif %}
    </div>
{% endblock %}

inventarioKK/templates/equipo/descripcion_equipo.html
{% extends "equipo/layout_base_equipo.html"%}
{% load static %}
{% block title %}Descripcion{% endblock %}
{% block body %}
<br>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <!--Tabla-->
            {% if descripcion_equipo %}
                <table class="table table-bordered table-hover table-dark text-center">
                    <thead>
                    <tr>
                        <th scope="col">Atributos</th>
                        <th scope="col">Datos</th>
                    </tr>
                    </thead>
                    <tbody>
                
                        <tr>
                            <th scope="row">Código</th> 
                            <td>{{descripcion_equipo.id_equipo}}</td>      
                        </tr>
                        <tr>
                            <th scope="row">Tipo de Equipo:</th>
                            <td>{{descripcion_equipo.id_tipo_equipo}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Marca:</th>
                            <td>{{descripcion_equipo.id_marca}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Estado:</th> 
                            <td>{{descripcion_equipo.id_estado_equipo}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Descripcion:</th>
                            <td>{{descripcion_equipo.descripcion}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Ubicación:</th>
                            <td>{{descripcion_equipo.id_ubicacion}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Edificio:</th>
                            <td>{{descripcion_equipo.id_ubicacion.id_edificio}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Acciones:</th>
                            <td><a href="{% url 'equipo:editar_equipo' descripcion_equipo.id_equipo %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
                            </td>
                        </tr>
            {% else %}
                <h1 class="text-center">No hay equipos registrados</h1>
            {% endif %}
                </tbody>
            </table>
            <div class="row justify-content-md-center">
                <button type="button" class="button button2 "><a href="{% url 'equipo:lista_de_equipos' %}" style="color: white;">Regresar</a></button>
                <button type="button" class="button button1 "><a href="{% url 'equipo:PDF' descripcion_equipo.id_equipo %}" style="color: white;">Imprimir</a></button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inventarioKK/templates/equipo/index.html
{% extends "equipo/layout_base_equipo.html"%}
{% load static %}
{% block title %}Equipo{% endblock %}
{% block body %}
<style>
  .search_submit{
    
    font-size: 15px;
   
  }
</style>

<br>
<div class = 'container'>
    <h1 class="text-center">Equipos en Existencia</h1>
      <div class = 'text-right'>
        <form action="{% url 'equipo:busqueda_equipo' %}" method="get">
          <input name="q" type="text" placeholder="Buscar equipo...">
          <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
        </form>
      </div>
      <br>
    <table class="table table-dark text-center table-hover">
        <thead>
          <tr>
            <th scope="col">N° Registro</th>
            <th scope="col">Marca</th>
            <th scope="col">Tipo de Equipo</th>
            <th scope="col">Ubicación</th>
            <th scope="col">Edificio</th>
            <th scope="col">Opciones</th>
          </tr>
        </thead>
        <tbody>
    {% if lista_equipo %}
          {% for tablaequipo in lista_equipo %}
          <tr>
            <th scope="row">{{tablaequipo.id_equipo}}</th>
            <td>{{tablaequipo.id_marca}}</td>
            <td>{{tablaequipo.id_tipo_equipo}}</td>
            <td>{{tablaequipo.id_ubicacion}}</td>
            <td>{{tablaequipo.id_ubicacion.id_edificio}}</td>
            <td><a href="{% url 'equipo:des_equipo' tablaequipo.id_equipo %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
                <a href="{% url 'equipo:editar_equipo' tablaequipo.id_equipo %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
            </td>
          </tr>
          {% endfor %}
    {% else %}
    <p>No hay registros de equipo</p>
    {% endif %}
        </tbody>
    </table>
   <!--Paginación-->
      <div class="row justify-content-md-center">
        <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Previous">
                Primero
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
           </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% ifequal num page_obj.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link current">
                {{ num }}
                <span class="sr-only">(current)</span>
            </a>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
          {% endifequal %} 
        {% endfor %}        

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Previous">
                Último
            </a>
          </li>
        {% endif %}
        </ul>
      </div>
</div>
{% endblock %}

inventarioKK/templates/equipo/inicio.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

    <title>Nucleus Admin</title>

		<meta name="description" content="Free download theme onepage, clean and modern responsive for all"/>
		<meta name="keywords" content="responsive, html5, onepage, themes, template, clean layout, free web"/>
		<meta name="author" content="Thomsoon.com"/>
		
		
		<link rel="stylesheet" type="text/css" href="{% static 'inicio/css/reset.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'inicio/css/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'inicio/css/style-responsive.css' %}" />				
		
</head>

<body>

<div class="container">


<!-- section start-page -->

  <section class="start-page parallax-background" id="home">
  
    <div class="opacity"></div>
      <div class="content">
        <div class="text">
        
          <h1>NUCLEUS<br/>
          TU MEJOR OPCION</h1>
          <p>Bienvenid@ {{ user.get_username }}
          <br>
          <br>
          {% if user.is_authenticated %}
            
            <a href="{% url 'logout'%}?next={{request.path}}"style="color:white">Logout</a>
            {% else %}
            <a href="{% url 'login'%}?next={{request.path}}"style="color:white">Login</a>
            {% endif %} 
          </p>
          
          
          <a href="#about-us"><div class="read-more">PRINCIPIOS</div></a>
          
        </div>
        <div class="arrow-down"></div>
      </div>
  
  </section>

  <!-- section menu mobile -->
  
  <section class="menu-media">
  
    <div class="menu-content">
    
      
      <div class="icon"><a href="#"><img src="img/icons/menu-media.png"/></a></div>
    
    </div>
   
  </section>
  
    <ul class="menu-click">
        <a href="#about-us"><li href="#about-us">ABOUT US</li></a>
        <a href="#portfolio"><li href="#portfolio">PORTFOLIO</li></a>
        <a href="#contact"><li href="#contact">CONTACT</li></a>
    
    </ul>
   

   
  <!-- section menu -->
  
  <section class="menu">

    <div class="menu-content">
    
    <div class="logo"><img src="{% static 'img\cube.png' %}" alt="cubo" width="20" height="20" >Nucleus</div>
    
      <ul id="menu">
        <li><a href="{% url 'equipo:lista_de_equipos' %}">EQUIPOS</a></li>
        <li><a href="{% url 'empleado:mensaje_empleado' %}">EMPLEADOS</a></li>
        <li><a href="{% url 'mantenimiento:index' %}">MANTENIMIENTO</a></li>
        <li><a href="{% url 'mantenimiento:index_bodega' %}">BODEGA</a></li>
        
        <li> <span class="navbar-text">
            
    
          </span></li>
      </ul>
     
    
    </div>
  
  
  </section>


  <!-- section about us -->
  
  <section class="about-us" id="about-us">
  
    <h1>NUESTRA MISION</h1>
    <hr/>
    <p class="title">LA ADMINISTRACION DE NUESTROS EQUIPOS Y RECURSOS ES PIONERA A NIVEL NACIONAL</p>
  
      <div class="column-one">
  
        <div class="circle-one"></div>
    
          <h2>CALIDAD<br/>ASEGURADA</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
    
      </div>
  
      <div class="column-two">
  
        <div class="circle-two"></div>
    
          <h2>MANTENIMIENTO<br/>OPTIMO</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
    
      </div>
  
  
      <div class="column-three">
  
        <div class="circle-three"></div>
    
        <h2>RECURSO<br/>EFICIENTE</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
    
    </div>  
    

  </section>
  
  <div class="clear"></div>  

  

    <section class="footer">
    
      <div class="margin">
      
        <div class="menu-footer">
        
        <a>Home</a>
        <a>Privacy policy</a>
        <a>RSS</a>
        <a>Facebook</a>
        
        </div>
        
          <div class="copyright">2020. All Rights Reserved</div>        

      </div>
    
    
    </section>    
    

</div>



	<!-- Scripts -->
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> <!-- jQuery -->
	<script src="js/jquery.parallax.js"></script> <!-- jQuery Parallax -->
	<script src="js/jquery.nicescroll.js"></script> <!-- jQuery NiceScroll -->
	<script src="js/jquery.sticky.js"></script> <!-- jQuery Stick Menu -->
	<script src="js/script.js"></script> <!-- All script -->

</body>

</html>

inventarioKK/templates/equipo/layout_base_equipo.html
{% extends "layout_base.html"%}
{% block link_css %} 
    {% load static %}
    <link rel="stylesheet" href="{% static 'equipo/css/estilos.css' %}"> 
{% endblock %}
{% block title %}{% endblock %}
{% block body %}{% endblock %}