inventarioKK/empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleado'
urlpatterns = [
    path('', views.Indice.as_view(), name='mensaje_empleado'),
    path('busqueda_empleado/', views.BusquedaEmpleado.as_view(), name='busqueda_empleado'),
    path('nuevo_empleado/', views.CrearEmpleado.as_view(), name='nuevo_empleado'),
    path('generador/', views.generador, name='generador'),
    path('<str:pk>/', views.DescripcionEmpleado.as_view(), name='des_em'),
    path('editar_empleado/<str:pk>/', views.EditarEmpleado.as_view(), name='editar_empleado'),
    path('eliminar_empleado/<str:pk>/', views.EliminarEmpleado.as_view(), name='eliminar_empleado'),
]

inventarioKK/equipo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

app_name = 'equipo'
urlpatterns = [
    path('', views.ListaDeEquipos.as_view(), name='lista_de_equipos'),
    path('inicio/', views.Inicio.as_view(), name='inicio'),
    path('nuevo_equipo/', views.EquipoCreate.as_view(), name='nuevo_equipo'),
    path('busqueda_equipo/', views.BusquedaEquipo.as_view(), name='busqueda_equipo'),
    path('generador/', views.generador, name='generador'),
    path('<str:pk>/', views.DescripcionEquipo.as_view(), name='des_equipo'),
    path('editar_equipo/<str:pk>/', views.EquipoUpdate.as_view(), name='editar_equipo'),
    
]

inventarioKK/inventarioKK/urls.py
from django.contrib.auth.views import LoginView, logout_then_login, login_required
"""inventarioKK URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from equipo import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('empleado/', include('empleado.urls')),
    path('equipo/', include('equipo.urls')),
    path('mantenimiento/', include('mantenimiento.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.Inicio.as_view(), name = 'inicio'),
]

inventarioKK/empleado/models.py
from django.db import models
from equipo.models import Ubicacion

# Create your models here.
class Cargo(models.Model):
    id_cargo = models.AutoField(primary_key=True)
    nombre_cargo = models.CharField(max_length=45)
    salario = models.CharField(max_length=45)

    class Meta:
        managed = True
        db_table = 'cargo'

    def __str__(self):
        return self.nombre_cargo


class Sexo(models.Model):
    id_sexo = models.AutoField(primary_key=True)
    nombre_sexo = models.CharField(max_length=45)

    class Meta:
        managed = True
        db_table = 'sexo'

    def __str__(self):
        return self.nombre_sexo

class EstadoEmpleado(models.Model):
    id_estado_empleado = models.AutoField(primary_key=True)
    nombre_estado_empleado = models.CharField(max_length=45)

    class Meta:
        managed = True
        db_table = 'estado_empleado'

    def __str__(self):
        return self.nombre_estado_empleado


class Empleado(models.Model):
    id_empleado = models.CharField(primary_key=True, max_length= 7)
    nombre = models.CharField(max_length=45)
    apellido = models.CharField(max_length=45)
    fecha_nacimiento = models.DateField()
    dui = models.CharField(max_length=10)
    nit = models.CharField(max_length=17)
    telefono_fijo = models.CharField(max_length=9, blank=True, null=True)
    id_cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, db_column='id_cargo')
    id_sexo = models.ForeignKey(Sexo, on_delete=models.CASCADE, db_column='id_sexo')
    id_estado_empleado = models.ForeignKey(EstadoEmpleado, on_delete=models.CASCADE, db_column='id_estado_empleado')
    id_ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE, db_column='id_ubicacion')

    class Meta:
        managed = True
        db_table = 'empleado'
        unique_together = (('id_empleado', 'id_cargo', 'id_sexo'),)

    def __str__(self):
        return str(self.id_empleado) + " - " + self.nombre

inventarioKK/empleado/forms.py
'''Formularios de Empleado'''
from django import forms
from .models import Empleado
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from datetime import date

class EmpleadoForm(forms.ModelForm):
    """Formulario para agregar un nuevo empleado"""
    class Meta:
        """Especificaciones"""
        model = Empleado

        fields = [
            'id_empleado',
            'nombre',
            'apellido',
            'fecha_nacimiento',
            'dui',
            'nit',
            'telefono_fijo',
            'id_cargo',
            'id_sexo',
            'id_estado_empleado',
            'id_ubicacion',
        ]

        labels = {
            'id_empleado':'Codigo',
            'nombre':'Nombres',
            'apellido':'Apellidos',
            'fecha_nacimiento':'Fecha de Nacimiento',
            'dui':'DUI',
            'nit':'NIT',
            'telefono_fijo':'Teléfono Fijo:',
            'id_cargo':'ID CARGO',
            'id_sexo':'Sexo',
            'id_estado_empleado':'Estado del Empleado',
            'id_ubicacion':'Ubicación',
        }
        widgets = {
            'id_empleado':forms.TextInput(attrs={'class':'form-control',
                                            'type':'text',
                                            'placeholder':'codigo',
                                            'name':'codigo',
                                            'id':'codigo',
                                            'readonly':'readonly'}),
            'nombre':forms.TextInput(attrs={'class':'form-control',
                                            'type':'text',
                                            'placeholder':'Nombres',
                                            'name':'nombre',
                                            'id':'nombre',
                                            'onkeyup':'PasarValor("nombre","apellido","codigo","/empleado/generador/")'}),
            'apellido':forms.TextInput(attrs={'class':'form-control',
                                              'type':'text',
                                              'placeholder':'Apellidos',
                                              'name':'apellido',
                                              'id':'apellido',
                                              'onkeyup':'PasarValor("nombre","apellido","codigo","/empleado/generador/")'}),
            'fecha_nacimiento':forms.TextInput(attrs={'class':'form-control',
                                                      'type':'date',
                                                      'placeholder':'Fecha',
                                                      'name':'fecha_nacimiento'}),
            'dui':forms.TextInput(attrs={'type':'number',
                                                    'class':'form-control',
                                                    'name':'dui',
                                                    'placeholder':'########'}),
            'nit':forms.TextInput(attrs={'type':'number',
                                                    'class':'form-control',
                                                    'name':'nit',
                                                    'placeholder':'########'}),
            'telefono_fijo':forms.TextInput(attrs={'type':'number',
                                                    'class':'form-control',
                                                    'name':'telefono_fijo',
                                                    'placeholder':'########'}),
            'id_cargo':forms.Select(attrs={'class':'custom-select',
                                          'name':'cargo'}),
            'id_sexo':forms.Select(attrs={'class':'custom-select',
                                          'name':'sexo'}),
            'id_estado_empleado':forms.Select(attrs={'class':'custom-select',
                                          'name':'estado_empleado'}),
            'id_ubicacion':forms.Select(attrs={'class':'custom-select',
                                          'name':'ubicacion'}),
        }

    def clean_fecha_nacimiento(self):
        cleaned_data = super().clean()
        dob = cleaned_data.get("fecha_nacimiento")
        today = date.today()
        if (dob.year + 18, dob.month, dob.day) > (today.year, today.month, today.day):
            raise forms.ValidationError('Must be at least 18 years old to register')
        return dob
       

inventarioKK/empleado/views.py
"""Vistas de la Aplicacion Empleado"""
from django.views import generic
from django.urls import reverse_lazy
from django.db.models import Q
from .models import Empleado
from .forms import EmpleadoForm
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class Indice(LoginRequiredMixin, generic.ListView):
    """Vista Genèrica de Tabla de Empleados"""
    template_name = 'empleado/e_index.html'
    context_object_name = 'lista_empleado'
    model = Empleado
    paginate_by = 5

class DescripcionEmpleado(LoginRequiredMixin, generic.DetailView):
    """Muestra una descripcion de cada Empleado"""
    template_name = 'empleado/descripcion_e.html'
    context_object_name = 'descripcion_empleado'
    model = Empleado

class CrearEmpleado(LoginRequiredMixin, generic.CreateView):
    """Muestra el formulario para crear un nuevo Empleado"""
    model = Empleado
    form_class = EmpleadoForm
    template_name = 'empleado/nuevo_empleado.html'
    success_url = reverse_lazy('empleado:mensaje_empleado')

    def post(self, request, *args, **kwargs):
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            book = form.save()
            book.save()
            return HttpResponseRedirect(reverse_lazy('empleado:mensaje_empleado'))
        else:
            return render(request, 'empleado/nuevo_empleado.html',
                          {'form': form, 'error_date': 'Debes ingresar una fecha válida'})

class EditarEmpleado(LoginRequiredMixin, generic.UpdateView):
    """Actualiza el registro de un Empleado"""
    model = Empleado
    form_class = EmpleadoForm
    template_name = 'empleado/nuevo_empleado.html'
    success_url = reverse_lazy('empleado:mensaje_empleado')

class EliminarEmpleado(LoginRequiredMixin, generic.DeleteView):
    """Elimina un Empleado"""
    model = Empleado
    context_object_name = 'descripcion_empleado'
    template_name = 'empleado/eliminar_empleado.html'
    success_url = reverse_lazy('empleado:mensaje_empleado')

class BusquedaEmpleado(LoginRequiredMixin, generic.ListView):
    """Busca un Empleado"""
    model = Empleado
    context_object_name = 'eliminacion_empleado'
    template_name = 'empleado/busqueda_empleado.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Empleado.objects.filter(
           Q(id_empleado__icontains=query) | Q(nombre__icontains=query) | Q(apellido__icontains=query)| 
           Q(dui__icontains=query) | Q(nit__icontains=query) | Q(fecha_nacimiento__icontains=query)| 
           Q(telefono_fijo__icontains=query) | Q(id_ubicacion__nombre_ubicacion__icontains=query) |
           Q(id_ubicacion__id_edificio__nombre_edificio__icontains=query)
        )
        return object_list

def generador(request):
    """
    Termina de generar codigo
    """
    if request.method == 'POST':
        print('llego')
        if 'letras' in request.POST:
            letras = request.POST['letras'].upper()
            anio = str(date.today().year)[:2]
            numero = str(Empleado.objects.filter(id_empleado__startswith=letras+anio).count()+1).zfill(3)
            codigo = letras+anio+numero
            return HttpResponse(codigo)
    return HttpResponse('FAIL!!!!!')

inventarioKK/templates/empleado/busqueda_empleado.html
{% extends "empleado/layout_base_empleado.html"%}
{% block title %}Resultados de la Busqueda{% endblock %}
{% load static %}
{% block body %}
<style>
  
  
  .search_submit{
      
      font-size: 15px;
     
    }
  
  </style>
<br>
<div class="container">
   
    <h1 class="text-center">Resultados de la Búsqueda</h1>
    <!--SearchBox con su respectivo Botón-->
<div class="text-right">
<form action="{% url 'empleado:busqueda_empleado' %}"  method="get">
    <input name="q" type="text" placeholder="Buscar empleado...">
    <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
</form>
</div>

<br>
        <div class="row justify-content-md-center text-right">
            <button class="button button2 align-right"><a href="{% url 'empleado:mensaje_empleado' %}" style="color: white;">Regresar</a></button>
        </div>
 <!--Tabla-->
    {% if object_list %}
    <table class="table table-bordered text-center table-hover table-dark">
        <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Ubicación</th>
            <th scope="col">Edificio</th>
            <th scope="col">Detalles</th>
          </tr>
        </thead>
        <tbody>

    {% for empleado in object_list %}
        
    <tr>
      <th scope="row">{{empleado.id_empleado}}</th>
      <td>{{empleado.nombre}}</td>
      <td>{{empleado.apellido}}</td>
      <td>{{empleado.id_ubicacion}}</td>
      <td>{{empleado.id_ubicacion.id_edificio}}</td>
      <td><a href="{% url 'empleado:des_em' empleado.id_empleado %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
          <a href="{% url 'empleado:editar_empleado' empleado.id_empleado %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
          <a href="{% url 'empleado:eliminar_empleado' empleado.id_empleado %}"><img src="{% static 'bootstrap/icons/trash.svg' %}" alt="My image" width="30px"></a>

      </td>
    </tr>
    {% endfor %}
{% else %}
<div class="text-center">
<h1>No hay coincidencias!</h1>
<img src="{% static 'img\rocket.gif' %}" alt="cohete">

</div>
{% endif %}
</tbody>
</table>
    </div>
{% endblock %}

inventarioKK/templates/empleado/descripcion_e.html
{% extends "empleado/layout_base_empleado.html"%}
{% block title %}Descripcion{% endblock %}
{% load static %}
{% block body %}
    <br>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-5">
                <!--Tabla-->
                {% if descripcion_empleado %}
                <table class="table table-bordered table-hover table-dark text-center">
                    <thead>
                    <tr>
                        <th scope="col">Atributos</th>
                        <th scope="col">Datos</th>
                    </tr>
                    </thead>
                    <tbody>
                
                        <tr>
                            <th scope="row">Código</th> 
                            <td>{{descripcion_empleado.id_empleado}}</td>      
                        </tr>
                        <tr>
                            <th scope="row">Nombre(s):</th>
                            <td>{{descripcion_empleado.nombre}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Apellidos:</th>
                            <td>{{descripcion_empleado.apellido}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Fecha de Nacimiento:</th> 
                            <td>{{descripcion_empleado.fecha_nacimiento}}</td>
                        </tr>
                        <tr>
                            <th scope="row">DUI:</th>
                            <td>{{descripcion_empleado.dui}}</td>
                        </tr>
                        <tr>
                            <th scope="row">NIT:</th>
                            <td>{{descripcion_empleado.nit}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Teléfono:</th>
                            <td>{{descripcion_empleado.telefono_fijo}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Cargo:</th>
                            <td>{{descripcion_empleado.id_cargo}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Sexo:</th>
                            <td>{{descripcion_empleado.id_sexo}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Estado:</th>
                            <td>{{descripcion_empleado.id_estado_empleado}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Ubicación:</th>
                            <td>{{descripcion_empleado.id_ubicacion}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Edificio:</th>
                            <td>{{descripcion_empleado.id_ubicacion.id_edificio}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Acciones:</th>
                            <td><a href="{% url 'empleado:editar_empleado' descripcion_empleado.id_empleado %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
                                <a href="{% url 'empleado:eliminar_empleado' descripcion_empleado.id_empleado %}"><img src="{% static 'bootstrap/icons/trash.svg' %}" alt="My image" width="30px"></a>
                            </td>
                        </tr>
                {% else %}
                    <h1 class="text-center">No hay empleados registrados</h1>
                {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

inventarioKK/templates/empleado/e_index.html
{% extends "empleado/layout_base_empleado.html"%}
{% block title %}Empleado{% endblock %}
{% load static %}
{% block body %}
<style>
    .search_submit{
      
      font-size: 15px;
     
    }
  </style>
<br>
<div class="container">
   
    <h1 class="text-center">Tabla de Empleados</h1>
    <!--SearchBox con su respectivo Botón-->
<div class="text-right">
<form action="{% url 'empleado:busqueda_empleado' %}"  method="get">
    <input name="q" type="text" placeholder="Buscar empleado...">
    <button id="search_submit" type="submit reset" class="btn btn-dark search_submit">Buscar</button>
</form>
</div>
<br>

    <!--Tabla-->
    {% if lista_empleado %}
    <table class="table table-bordered text-center table-hover table-dark">
        <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Ubicación</th>
            <th scope="col">Edificio</th>
            <th scope="col">Opciones</th>
          </tr>
        </thead>
        <tbody>
    
            {% for tablaempleado in lista_empleado %}
            <tr>
             <th scope="row">{{tablaempleado.id_empleado}}</th>
             <td>{{tablaempleado.nombre}}</td>
             <td>{{tablaempleado.apellido}}</td>
             <td>{{tablaempleado.id_ubicacion}}</td>
             <td>{{tablaempleado.id_ubicacion.id_edificio}}</td>
             <td><a href="{% url 'empleado:des_em' tablaempleado.id_empleado %}"><img src="{% static 'bootstrap/icons/info-circle.svg' %}" alt="My image" width="30px"></a>
                 <a href="{% url 'empleado:editar_empleado' tablaempleado.id_empleado %}"><img src="{% static 'bootstrap/icons/pencil-square.svg' %}" alt="My image" width="30px"></a>
                 <a href="{% url 'empleado:eliminar_empleado' tablaempleado.id_empleado %}"><img src="{% static 'bootstrap/icons/trash.svg' %}" alt="My image" width="30px"></a>

             </td>
            </tr>
            {% endfor %}
    {% else %}
        <h1 class="text-center">No hay empleados registrados</h1>
    {% endif %}
        </tbody>
    </table>

    <!--Botón Agregar Empleado
     <div class="row justify-content-md-center">
        <button class="button button2 "><a href="{% url 'empleado:nuevo_empleado' %}" style="color:white">Agregar Empleado</a></button>
    </div>
    <br>-->

    <!--Paginación-->
    <div class="row justify-content-md-center">
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="Previous">
                    Primera
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% ifequal num page_obj.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link current">
                    {{ num }}
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endifequal %} 
        {% endfor %}        

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Previous">
                    Última
                </a>
            </li>
        {% endif %}
        </ul>
    </div>
    </div>
{% endblock %}

inventarioKK/templates/empleado/eliminar_empleado.html
{% extends 'empleado/layout_base_empleado.html' %}
{% block title %}Eliminar Empleado >:){% endblock %}
{% load static %}
{% block body %}
<div class="container">
    <div class="jumbotron">
        <form method="POST">
            {% csrf_token %}
            <h3><strong>¿Borrar de forma permanente a éste empleado? {{ descripcion_empleado.nombre }}?</strong></h3>
            <!--<p>Esta acción causara la eliminación de otros registro relacionados.</p>
            {% if paciente_seleccionado.familiar_set.all %}
            <h5><strong>Familiares que serán eliminados:</strong></h5>
            <ul>
            {% for familiar in paciente_seleccionado.familiar_set.all %}
                <li>{{familiar.nombre}}</li>
            {% endfor %}    
            </ul>
            {% endif %}-->
            <button class="btn btn-danger btn-lg" type="submit" value="Confirm">Sí, elimnar</button>
            <button class="button button1" type="button" ><a href="{% url 'empleado:mensaje_empleado' %}" style="color:white">Cancelar</a></button>
        </form>
    </div>
</div>
{% endblock %}

inventarioKK/templates/empleado/layout_base_empleado.html
{% extends "layout_base.html"%}
{% block link_css %} 
    {% load static %}
    <link rel="stylesheet" href="{% static 'empleado/css/empleadostyle.css' %}"> 
{% endblock %}
{% block title %}{% endblock %}
{% block body %}{% endblock %}

inventarioKK/templates/empleado/nuevo_empleado.html
{% extends 'empleado/layout_base_empleado.html' %}
{% block title %}Nuevo Empleado{% endblock %}
{% load static %}
{% block body %}
    <div class="container margen-arriba">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form method="POST">
            {% csrf_token %}
            <!-- titlulo del form -->
            <div class="form-group">
                <h1>Agregar Empleado</h1>
            </div>
            <!-- Codigo -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="id_tipo_equipo">Codigo:</label>
                    </div>
                    <div class="col-md-6">
                        {{form.id_empleado}}
                    </div>
                </div>
            </div>
            <!-- Nombres -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="id_tipo_equipo">Nombres:</label>
                    </div>
                    <div class="col-md-6">
                        {{form.nombre}}
                    </div>
                </div>
            </div>
            <!-- Apellidos -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="id_marca">Apellidos:</label>
                    </div>
                    <div class="col-md-3">
                        {{ form.apellido }}
                    </div>
                </div>
            </div>
            <!-- fecha_nacimiento -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="id_estado_equipo">Fecha de Nacimiento:</label>
                    </div>
                    <div class="col-md-3">
                        {{ form.fecha_nacimiento}}
                    </div>
                    <!--mensaje de error si se quiere ingresar un menor de edad o una fecha en el futuro-->
                    {% if error_date %}
                    <small id="passwordHelpInline" class="letra-roja">
                        <strong>{{error_date}}</strong>
                    </small>
                    {% endif %}
                </div>
            </div>
            <!-- DUI -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="id_ubicacion">DUI:</label>
                    </div>
                    <div class="col-md-3">
                        {{ form.dui }}
                    </div>
                </div>
            </div>
            <!-- NIT -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">NIT:</label>
                    </div>
                    <div class="col-md-3">
                    {{ form.nit }}
                    </div>
                </div>
            </div>
            <!-- Telefono Fijo -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">Telefono Fijo:</label>
                    </div>
                    <div class="col-md-3">
                    {{ form.telefono_fijo }}
                    </div>
                </div>
            </div>
            <!-- ID Cargo -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">Cargo:</label>
                    </div>
                    <div class="col-md-3">
                    {{ form.id_cargo }}
                    </div>
                </div>
            </div>
            <!-- Sexo -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">Sexo:</label>
                    </div>
                    <div class="col-md-3">
                    {{ form.id_sexo }}
                    </div>
                </div>
            </div>
            <!-- Estado Empleado -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">Estado del Empleado:</label>
                    </div>
                    <div class="col-md-3">
                    {{ form.id_estado_empleado }}
                    </div>
                </div>
            </div>
            <!-- Ubicacion -->
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">Ubicacion:</label>
                    </div>
                    <div class="col-md-3">
                    {{ form.id_ubicacion }}
                    </div>
                </div>
            </div>
            <p><br></p>
            <div class="row justify-content-md-center">
            <button type="submit" class="button button2" value="Agregar">Guardar</button>
            <button  type ="button" class="button button1"><a href="{% url 'empleado:mensaje_empleado' %}" style="color:white">Cancelar</a></button>
            <button type="reset" class="button button2" value="Resetear">Reiniciar</button>
            </div>
        </form>
    </div>
{% endblock %}