inventarioKK/empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleado'
urlpatterns = [
    path('', views.Indice.as_view(), name='mensaje_empleado'),
    path('busqueda_empleado/', views.BusquedaEmpleado.as_view(), name='busqueda_empleado'),
    path('nuevo_empleado/', views.CrearEmpleado.as_view(), name='nuevo_empleado'),
    path('generador/', views.generador, name='generador'),
    path('<str:pk>/', views.DescripcionEmpleado.as_view(), name='des_em'),
    path('editar_empleado/<str:pk>/', views.EditarEmpleado.as_view(), name='editar_empleado'),
    path('eliminar_empleado/<str:pk>/', views.EliminarEmpleado.as_view(), name='eliminar_empleado'),
]

inventarioKK/equipo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

app_name = 'equipo'
urlpatterns = [
    path('', views.ListaDeEquipos.as_view(), name='lista_de_equipos'),
    path('inicio/', views.Inicio.as_view(), name='inicio'),
    path('nuevo_equipo/', views.EquipoCreate.as_view(), name='nuevo_equipo'),
    path('busqueda_equipo/', views.BusquedaEquipo.as_view(), name='busqueda_equipo'),
    path('generador/', views.generador, name='generador'),
    path('<str:pk>/', views.DescripcionEquipo.as_view(), name='des_equipo'),
    path('editar_equipo/<str:pk>/', views.EquipoUpdate.as_view(), name='editar_equipo'),
    
]

inventarioKK/inventarioKK/urls.py
from django.contrib.auth.views import LoginView, logout_then_login, login_required
"""inventarioKK URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from equipo import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('empleado/', include('empleado.urls')),
    path('equipo/', include('equipo.urls')),
    path('mantenimiento/', include('mantenimiento.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.Inicio.as_view(), name = 'inicio'),
]

inventarioKK/mantenimiento/urls.py
"""urls de mantenimiento"""
from django.urls import path
from . import views

app_name = 'mantenimiento'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('generador/', views.generador, name='generador'),
    path('generador_bodega/', views.generador_bodega, name='generador_bodega'),
    path('busqueda_mantenimiento/', views.BusquedaMantenimiento.as_view(), name='busqueda_mantenimiento'),
    path('nuevo_mantenimiento/', views.MantenimientoCreate.as_view(), name='nuevo'),
    path('index_bodega/', views.BodegaIndex.as_view(), name='index_bodega'),
    path('nuevo_bodega/', views.BodegatoCreate.as_view(), name='nuevo_bodega'),
    path('busqueda_bodega/', views.BodegaBusqueda.as_view(), name='busqueda_bodega'),
    path('nuevo_mantenimientoporbodega/', views.MantenimientoPorBodegaCreate.as_view(), name='nuevo_mantenimientoporbodega'),
    path('editar_mantenimiento/<str:pk>/', views.MantenimientoUpdate.as_view(), name='editar'),
    path('descripcion_mantenimiento/<str:pk>/', views.DescripcionMatenimiento.as_view(), name='descripcion'),
    path('<str:pk>/', views.DescripcionMatenimiento.as_view(), name='descripcion'),
    path('editar_bodega/<str:pk>/', views.BodegatoUpdate.as_view(), name='editar_bodega'),
    path('descripcion_bodega/<str:pk>/', views.BodegaDescripcion.as_view(), name='descripcion_bodega'),
    


]

inventarioKK/templates/layout_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'js/utils.js' %}"></script>
    {% block link_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'inicio' %}"><img src="{% static 'img\cube.png' %}" alt="cubo" width="20" height="20">Nucleus SV</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Equipos
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'equipo:lista_de_equipos' %}">Indice</a>
                    <a class="dropdown-item" href="{% url 'equipo:nuevo_equipo' %}">Agregar Equipo</a>
                  </div>
                </div>
            
            <li class="nav-item active">
              <div class="dropdown show">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Empleados
                </a>
              
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'empleado:mensaje_empleado' %}">Indice</a>
                  <a class="dropdown-item" href="{% url 'empleado:nuevo_empleado' %}">Agregar</a>
    
                </div>
              </div>
            </li>
            <li class="nav-item active">
              <div class="dropdown show">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Mantenimiento
                </a>
              
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'mantenimiento:index' %}">Indice</a>
                  <a class="dropdown-item" href="{% url 'mantenimiento:nuevo' %}">Agregar</a>
                </div>
              </div>
            </li>
            <li class="nav-item active">
              <div class="dropdown show">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Bodega
                </a>
              
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'mantenimiento:index_bodega' %}">Indice</a>
                  <a class="dropdown-item" href="{% url 'mantenimiento:nuevo_bodega' %}">Agregar</a>
                  <a class="dropdown-item" href="{% url 'mantenimiento:nuevo_mantenimientoporbodega' %}">Asignar recurso</a>
                </div>
              </div>
            </li>
          </ul>
          <span class="navbar-text">
            {% if user.is_authenticated %}
              Usuario: {{ user.get_username }}
              <a href="{% url 'logout'%}?next={{request.path}}">| Logout</a>
            {% else %}
              <a href="{% url 'login'%}?next={{request.path}}">Login</a>
            {% endif %} 

          </span>
        </div>
    </nav>
    {% block body %}{% endblock %}
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>